name: Pulumi Deploy (Dev)

on:
  push:
    branches:
      - dev

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_OBJECT_ID: ${{ secrets.ARM_CLIENT_OBJECT_ID }}

jobs:
  up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Setup Pulumi
        uses: pulumi/actions@v4

      - name: Login to Pulumi
        run: pulumi login

      - name: Set stack
        run: pulumi stack select parkway-org/parkway/parkway-dev

      - name: Set config values
        run: |
          pulumi config set location centralus --stack parkway-dev
          pulumi config set resourcePrefix parkway-dev --stack parkway-dev
          pulumi config set sqlAdminUsername sqladmin --stack parkway-dev
          pulumi config set sqlAdminPassword ${{ secrets.SQL_ADMIN_PASSWORD }} --secret --stack parkway-dev
          pulumi config set tenantId ${{ env.ARM_TENANT_ID }} --stack parkway-dev

      - name: Install dependencies
        run: dotnet restore

      - name: Build Pulumi project
        run: dotnet build

      - name: Deploy infrastructure
        run: pulumi up --yes
